# active profile
# spring.profiles.active=@activeProfile@

spring:
  application:
    name: My Lotto Test
  profiles.active: local
  profiles:
    include: 'datasource,redis'

---
spring:
  profiles: local

server:
  port: 8080
---

spring:
  profiles: dev

server:
  port: 80
---

spring:
  profiles: qa

server:
  port: 80
---

spring:
  profiles: release

server:
  port: 80

# JSP 용 ViewResolver설정
# spring.view.prefix:/WEB-INF/view/
# spring.view.suffix:.jsp
