# active profile
# spring.profiles.active=@activeProfile@

spring:
  profiles.active: local

---
spring:
  profiles: local

person.name: This is local

---

spring:
  profiles: dev

person.name: This is dev

---

spring:
  profiles: qa

person.name: This is qa

---

spring:
  profiles: release

person.name: This is release


# JSP 용 ViewResolver설정
# spring.view.prefix:/WEB-INF/view/
# spring.view.suffix:.jsp
