# active profile
# spring.profiles.active=@activeProfile@

spring:
  application:
    name: My Lotto Test
#  profiles.active: local
  profiles:
    include: 'datasource,redis,personnel'

---
spring:
  profiles: local
    # include: 'datasource,redis,personnel'

server:
  port: 8080
---

spring:
  profiles: dev
  include: 'datasource,redis,personnel'
  # include: 'datasource,redis,personnel'

server:
  port: 80
---

spring:
  profiles: qa
    # include: 'datasource,redis,personnel'

server:
  port: 80
---

spring:
  profiles: release
    # include: 'datasource,redis,personnel'


server:
  port: 80

# JSP 용 ViewResolver설정
# spring.view.prefix:/WEB-INF/view/
# spring.view.suffix:.jsp
