# active profile
# spring.profiles.active=@activeProfile@

spring:
  application:
    name: My Lotto Test
  profiles.active: local
  profiles:
#    include: database.yml

---
spring:
  profiles: local

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/?characterEncoding=UTF-8&useSSL=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useAffectedRows=true
    username: mytest
    password: mysql123!
    tomcat:
      initial-size: 1
      min-idle: 1
      # Maximum number of active connections that can be allocated from this pool at the same time.
      max-active: 4
      max-idle: 4
      # Number of ms to wait before throwing an exception if no connection is available.
      max-wait: 3000
      validation-query: SELECT 1
      # Validate the connection before borrowing it from the pool.
      test-on-borrow: true

  redis:
      host: localhost
      port: 6379
      timeout: 3000

server:
  port: 8080
---

spring:
  profiles: dev

  redis:
      host: localhost
      port: 6379
      timeout: 3000

server:
  port: 80
---

spring:
  profiles: qa

  redis:
      host: localhost
      port: 6379
      timeout: 3000

server:
  port: 80
---

spring:
  profiles: release

  redis:
      host: localhost
      port: 6379
      timeout: 3000

server:
  port: 80
---

# JSP 용 ViewResolver설정
# spring.view.prefix:/WEB-INF/view/
# spring.view.suffix:.jsp
